x-logging:
  logging: &default-logging
    driver: "local"
    options:
      max-size: "10m"
      max-file: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - label-studio-app
    volumes:
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/certs:/certs:ro
    #   Optional: Override nginx default conf
    #      - ./deploy/my.conf:/etc/nginx/nginx.conf
    # command: nginx
    networks:
      - main_network
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.label-studio-nginx.rule=Host(`label-studio.localhost`) || Host(`label-studio.${DOMAINNAME}`) || Host(`label-studio.ppsmartproduct.com`)"
      - "traefik.http.services.label-studio-nginx.loadbalancer.server.port=7080"

  label-studio-app:
    image: heartexlabs/label-studio:latest
    restart: always
    expose:
      - "7080"
    depends_on:
      - label-studio-db
    environment:
      - DJANGO_DB=postgresql
      - POSTGRE_NAME=${POSTGRE_NAME:-labelstudio}
      - POSTGRE_USER=${POSTGRE_USER:-postgres}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD:-}
      - POSTGRE_HOST=label-studio-db
      - POSTGRE_PORT=${POSTGRE_PORT:-5432}
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - LABEL_STUDIO_PORT=${LABEL_STUDIO_PORT:-7080}
    volumes:
      - ./mydata:/label-studio/data:rw
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - main_network
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.label-studio-app.rule=Host(`label-studio.localhost`) || Host(`label-studio.${DOMAINNAME}`)"
      - "traefik.http.services.label-studio-app.loadbalancer.server.port=7080"

  label-studio-db:
    image: postgres:11.5
    hostname: label-studio-db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRE_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD:-}
      - POSTGRES_DB=${POSTGRE_NAME:-labelstudio}
    networks:
      - main_network
    logging: *default-logging

  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-13T15-35-11Z
    command: server /data --console-address ":9009"
    restart: unless-stopped
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio_admin_do_not_use_in_production}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio_admin_do_not_use_in_production}
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    networks:
      - main_network
    logging: *default-logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=https
      - traefik.http.routers.minio.rule=Host(`minio.ppsmartbot.com`)
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

      - traefik.http.routers.minioadmin.entrypoints=https
      - traefik.http.routers.minioadmin.rule=Host(`minio-console.ppsmartbot.com`)
      - traefik.http.routers.minioadmin.service=minioadmin
      - traefik.http.services.minioadmin.loadbalancer.server.port=9009

  prometheus:
    image: quay.io/prometheus/prometheus:v2.37.1
    restart: unless-stopped
    volumes:
      - "./prometheus/minio/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - main_network
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`) || Host(`prometheus.${DOMAINNAME}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

networks:
  main_network:
    external: true
    name: main_network
    driver: bridge

volumes:
  minio-data:
  prometheus-data:
  pgdata:
